spring.application.name=ewsaly

# Server Configuration
server.port=9091

# MySQL Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA and Hibernate Configuration for MySQL
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace

api.prefix=/api/v1



auth.token.jwt-secret-key=${JWT_SECRET_KEY}
auth.token.expiration-in-mils=${JWT_EXPIRATION_TIME}

spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8