/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MyQrCodesRouteImport } from './routes/my-qr-codes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as QrCodesRouteImport } from './routes/qr-codes'
import { Route as ScanLogsRouteImport } from './routes/scan-logs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SCodeRouteImport } from './routes/s.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQrCodesRoute = MyQrCodesRouteImport.update({
  id: '/my-qr-codes',
  path: '/my-qr-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodesRoute = QrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanLogsRoute = ScanLogsRouteImport.update({
  id: '/scan-logs',
  path: '/scan-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/messages': typeof MessagesRoute
  '/my-qr-codes': typeof MyQrCodesRoute
  '/notifications': typeof NotificationsRoute
  '/qr-codes': typeof QrCodesRoute
  '/scan-logs': typeof ScanLogsRoute
  '/settings': typeof SettingsRoute
  '/s/$code': typeof SCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/messages': typeof MessagesRoute
  '/my-qr-codes': typeof MyQrCodesRoute
  '/notifications': typeof NotificationsRoute
  '/qr-codes': typeof QrCodesRoute
  '/scan-logs': typeof ScanLogsRoute
  '/settings': typeof SettingsRoute
  '/s/$code': typeof SCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/messages': typeof MessagesRoute
  '/my-qr-codes': typeof MyQrCodesRoute
  '/notifications': typeof NotificationsRoute
  '/qr-codes': typeof QrCodesRoute
  '/scan-logs': typeof ScanLogsRoute
  '/settings': typeof SettingsRoute
  '/s/$code': typeof SCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacts'
    | '/messages'
    | '/my-qr-codes'
    | '/notifications'
    | '/qr-codes'
    | '/scan-logs'
    | '/settings'
    | '/s/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacts'
    | '/messages'
    | '/my-qr-codes'
    | '/notifications'
    | '/qr-codes'
    | '/scan-logs'
    | '/settings'
    | '/s/$code'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contacts'
    | '/messages'
    | '/my-qr-codes'
    | '/notifications'
    | '/qr-codes'
    | '/scan-logs'
    | '/settings'
    | '/s/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactsRoute: typeof ContactsRoute
  MessagesRoute: typeof MessagesRoute
  MyQrCodesRoute: typeof MyQrCodesRoute
  NotificationsRoute: typeof NotificationsRoute
  QrCodesRoute: typeof QrCodesRoute
  ScanLogsRoute: typeof ScanLogsRoute
  SettingsRoute: typeof SettingsRoute
  SCodeRoute: typeof SCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-qr-codes': {
      id: '/my-qr-codes'
      path: '/my-qr-codes'
      fullPath: '/my-qr-codes'
      preLoaderRoute: typeof MyQrCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-codes': {
      id: '/qr-codes'
      path: '/qr-codes'
      fullPath: '/qr-codes'
      preLoaderRoute: typeof QrCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-logs': {
      id: '/scan-logs'
      path: '/scan-logs'
      fullPath: '/scan-logs'
      preLoaderRoute: typeof ScanLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactsRoute: ContactsRoute,
  MessagesRoute: MessagesRoute,
  MyQrCodesRoute: MyQrCodesRoute,
  NotificationsRoute: NotificationsRoute,
  QrCodesRoute: QrCodesRoute,
  ScanLogsRoute: ScanLogsRoute,
  SettingsRoute: SettingsRoute,
  SCodeRoute: SCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
